name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main  # Change si ta branche principale a un autre nom

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Doxygen
        run: sudo apt-get install doxygen graphviz -y

      - name: Generate Doxygen documentation
        run: |
          cd doc
          doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html
          publish_branch: gh-pages
          force_orphan: true
          enable_jekyll: false
